apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/scc: restricted
  creationTimestamp: "2020-10-15T05:46:32Z"
  name: kubia
  namespace: myproject
  resourceVersion: "34389"
  selfLink: /api/v1/namespaces/myproject/pods/kubia
  uid: c79309ce-0ea9-11eb-bf70-7a3cabe63bfe
spec:
  containers:
    - image: "douglasdb/quarkus-hello:latest"
      imagePullPolicy: Always
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000140000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-27967
          readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: default-dockercfg-cnq9t
  nodeName: localhost
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000140000
    seLinuxOptions:
      level: "s0:c12,c4"
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
    - name: default-token-27967
      secret:
        defaultMode: 420
        secretName: default-token-27967
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-10-15T05:46:32Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2020-10-15T05:46:54Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2020-10-15T05:46:32Z"
      status: "True"
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        docker://dc6bbdc42ca45b1183bb849fbc85e106d6085fc01f2dd42a083d2a1e2c857b43
      image: "docker.io/douglasdb/quarkus-hello:latest"
      imageID: >-
        docker-pullable://docker.io/douglasdb/quarkus-hello@sha256:6d97330a014018c4df65a38a7940944bccaba4d0d3287b5bbb45180eb1eef995
      lastState: {}
      name: kubia
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: "2020-10-15T05:46:54Z"
  hostIP: 192.168.64.3
  phase: Running
  podIP: 172.17.0.9
  qosClass: BestEffort
  startTime: "2020-10-15T05:46:32Z"
