apiVersion: v1
kind: Pod
metadata:
  name: kubia-init
  spec:
    initContainers:
    - name: init-demo # 1nd Init Container
      image: luksa/init-demo:1.0
    - name: network-check # 2nd Init Container
      image: luksa/network-connectivity-checker:1.0
    containers:
    - name: kubia # 1nd Container
      image: luksa/kubia:1.0
      ports:
      - name: http
        containerPort: 8080
    - name: envoy # 2nd Container
      image: luksa/kubia-ssl-proxy:1.0
      ports:
      - name: https
        containerPort: 8443
      - name: admin
        containerPort: 9901
